[package]
name = "algorithmssite-page"
version = "0.1.0"
edition = "2021"


[lib]
path = "rust/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "*"
js-sys = "*"
web-sys = { version = "*", features = [
    "Document", "Window", "HtmlElement", "DomRect"
]}
